project:
  type: website
  render:
    - "*.qmd"
    - "!codes/"

website:
  title: "REL-Physique"
  navbar:
    title: false
    left:
      - href: index.qmd
        text: Accueil
      - about.qmd
      - minkowski.qmd
      - michelsonmorley.qmd
      - projectile.qmd
  page-footer: "Version 1.0 (mars 2026)"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    highlight-style: github



