project:
  type: website
  render:
    - "site/*.qmd"
    - "!codes/"

website:
  title: "REL_referentiels"
  navbar:
    title: false
    left:
      - href: site/index.qmd
        text: Accueil
      - site/about.qmd
      - site/minkowski.qmd
      - site/michelsonmorley.qmd
      - site/projectile.qmd
  page-footer: "Version 1.0 (mars 2026)"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    highlight-style: github



